//>>built
(function(l,x){var h,Da=function(){return"undefined"!==typeof y&&"function"!==typeof y?y:"undefined"!==typeof window?window:"undefined"!==typeof self?self:this}(),F=function(){},Ea=function(a){for(var b in a)return 0;return 1},ma={}.toString,B=function(a){return"[object Function]"==ma.call(a)},H=function(a){return"[object String]"==ma.call(a)},na=function(a){return"[object Array]"==ma.call(a)},r=function(a,b){if(a)for(var c=0;c<a.length;)b(a[c++])},n=function(a,b){for(var c in b)a[c]=b[c];return a},
u=function(a,b){return n(Error(a),{src:"dojoLoader",info:b})},bb=1,Fa=function(){return"_"+bb++},f=function(a,b,c){return Ga(a,b,c,0,f)},y=Da,w=y.document,cb=w&&w.createElement("DiV"),k=f.has=function(a){return B(G[a])?G[a]=G[a](y,w,cb):G[a]},G=k.cache=x.hasCache;B(l)&&(l=l(Da));k.add=function(a,b,c,d){(void 0===G[a]||d)&&(G[a]=b);return c&&k(a)};k.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);k("host-webworker")&&(n(x.hasCache,{"host-browser":0,dom:0,
"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1,"dojo-guarantee-console":0}),x.loaderPatch={injectUrl:function(a,b){try{importScripts(a),b()}catch(c){console.error(c)}}});for(var Ha in l.has)k.add(Ha,l.has[Ha],0,1);var p=0,I=[],oa=0,pa=F,Ia=F,W;f.isXdUrl=F;f.initSyncLoader=function(a,b,c){oa||(oa=a,pa=b,Ia=c);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:I,modules:m,execQ:q,getModule:z,injectModule:X,setArrived:J,signal:v,finishExec:N,
execModule:O,dojoRequirePlugin:oa,getLegacyMode:function(){return p},guardCheckComplete:P}};var db=location.protocol,Ja=location.host;f.isXdUrl=function(a){return/^\./.test(a)?!1:/^\/\//.test(a)?!0:(a=a.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(a[1]!=db||Ja&&a[2]!=Ja)};k.add("dojo-force-activex-xhr",!w.addEventListener&&"file:"==window.location.protocol);k.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(k("native-xhr")&&!k("dojo-force-activex-xhr"))W=function(){return new XMLHttpRequest};else{var eb=
["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],qa;for(h=0;3>h;)try{qa=eb[h++];new ActiveXObject(qa);break}catch(a){}W=function(){return new ActiveXObject(qa)}}f.getXhr=W;k.add("dojo-gettext-api",1);f.getText=function(a,b,c){var d=W();d.open("GET",Y(a),!1);d.send(null);if(200==d.status||!location.host&&!d.status)c&&c(d.responseText,b);else throw u("xhrFailed",d.status);return d.responseText};var fb=k("csp-restrictions")?function(){}:new Function("return eval(arguments[0]);");f.eval=function(a,
b){return fb(a+"\r\n//# sourceURL\x3d"+b)};var ra={},v=f.signal=function(a,b){var c=ra[a];r(c&&c.slice(0),function(a){a.apply(null,na(b)?b:[b])})},gb=f.on=function(a,b){var c=ra[a]||(ra[a]=[]);c.push(b);return{remove:function(){for(var a=0;a<c.length;a++)if(c[a]===b){c.splice(a,1);break}}}},Ka=[],hb={},La=[],C={},Ma=f.map={},Z=[],m={},sa="",D={},aa={},ba={},K=0,ca=function(a){var b,c,d,e;for(b in aa)c=aa[b],(d=b.match(/^url\:(.+)/))?D["url:"+Na(d[1],a)]=c:"*now"==b?e=c:"*noref"!=b&&(d=Q(b,a,!0),D[d.mid]=
D["url:"+d.url]=c);e&&e(ta(a));aa={}},Oa=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},ua=function(a,b){b.splice(0,b.length);for(var c in a)b.push([c,a[c],new RegExp("^"+Oa(c)+"(/|$)"),c.length]);b.sort(function(a,b){return b[3]-a[3]});return b},ib=function(a,b){r(a,function(a){b.push([H(a[0])?new RegExp("^"+Oa(a[0])+"$"):a[0],a[1]])})},Pa=function(a){var b=a.name;b||(b=a,a={name:b});a=n({main:"main"},a);a.location=a.location?a.location:b;a.packageMap&&(Ma[b]=
a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));C[b]=a},Qa=[],R=function(a,b,c){for(var d in a){"waitSeconds"==d&&(f.waitms=1E3*(a[d]||0));"cacheBust"==d&&(sa=a[d]?H(a[d])?a[d]:(new Date).getTime()+"":"");if("baseUrl"==d||"combo"==d)f[d]=a[d];if("async"==d){var e=a[d];f.legacyMode=p=H(e)&&/sync|legacyAsync/.test(e)?e:e?!1:"sync";f.async=!p}a[d]!==G&&(f.rawConfig[d]=a[d],"has"!=d&&k.add("config-"+d,a[d],0,b))}f.baseUrl||(f.baseUrl="./");/\/$/.test(f.baseUrl)||(f.baseUrl+="/");for(d in a.has)k.add(d,
a.has[d],0,b);r(a.packages,Pa);for(var g in a.packagePaths)r(a.packagePaths[g],function(a){var b=g+"/"+a;H(a)&&(a={name:a});a.location=b;Pa(a)});ua(n(Ma,a.map),Z);r(Z,function(a){a[1]=ua(a[1],[]);"*"==a[0]&&(Z.star=a)});ua(n(hb,a.paths),La);ib(a.aliases,Ka);if(b)Qa.push({config:a.config});else for(d in a.config)b=z(d,c),b.config=n(b.config||{},a.config[d]);a.cache&&(ca(),aa=a.cache,a.cache["*noref"]&&ca());v("config",[a,f.rawConfig])};k("dojo-cdn");var da=w.getElementsByTagName("script");h=0;for(var A,
L,ea,S;h<da.length;)if(A=da[h++],(ea=A.getAttribute("src"))&&(S=ea.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))&&(L=S[3]||"",x.baseUrl=x.baseUrl||L,K=A),ea=A.getAttribute("data-dojo-config")||A.getAttribute("djConfig"))ba=f.eval("({ "+ea+" })","data-dojo-config"),K=A;f.rawConfig={};R(x,1);k("dojo-cdn")&&((C.dojo.location=L)&&(L+="/"),C.dijit.location=L+"../dijit/",C.dojox.location=L+"../dojox/");R(l,1);R(ba,1);var T=function(a){P(function(){r(a.deps,X)})},Ga=function(a,b,c,d,e){var g;if(H(a)){if((g=z(a,
d,!0))&&g.executed)return g.result;throw u("undefinedModule",a);}na(a)||(R(a,0,d),a=b,b=c);if(na(a))if(a.length){c="require*"+Fa();for(var k,l=[],h=0;h<a.length;)k=a[h++],l.push(z(k,d));g=n(fa("",c,0,""),{injected:2,deps:l,def:b||F,require:d?d.require:f,gc:1});m[g.mid]=g;T(g);var r=U&&"sync"!=p;P(function(){O(g,r)});g.executed||q.push(g);M()}else b&&b();return e},ta=function(a){if(!a)return f;var b=a.require;b||(b=function(c,d,e){return Ga(c,d,e,a,b)},a.require=n(b,f),b.module=a,b.toUrl=function(b){return Na(b,
a)},b.toAbsMid=function(b){return va(b,a)},b.syncLoadNls=function(b){b=Q(b,a);var c=m[b.mid];if(!c||!c.executed)if(E=D[b.mid]||D["url:"+b.url])ga(E),c=m[b.mid];return c&&c.executed&&c.result});return b},q=[],ha=[],t={},kb=function(a){a.injected=1;t[a.mid]=1;a.url&&(t[a.url]=a.pack||1);Sa()},J=function(a){a.injected=2;delete t[a.mid];a.url&&delete t[a.url];Ea(t)&&(ia(),"xd"==p&&(p="sync"))},lb=f.idle=function(){return!ha.length&&Ea(t)&&!q.length&&!U},wa=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c][2].test(a))return b[c];
return 0},Ta=function(a){var b=[],c,d;for(a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&b.length&&".."!=d?(b.pop(),d=b[b.length-1]):"."!=c&&b.push(d=c);return b.join("/")},fa=function(a,b,c,d){var e=f.isXdUrl(d);return{pid:a,mid:b,pack:c,url:d,executed:0,def:0,isXd:e,isAmd:!!(e||C[a]&&C[a].isAmd)}},Ua=function(a,b,c,d,e,g,f,l,p){var m,Ra,h,n;n=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||n&&!b)return fa(0,a,0,a);a=Ta(n?b.mid+"/../"+a:a);if(/^\./.test(a))throw u("irrationalPath",
a);b&&(h=wa(b.mid,g));(h=(h=h||g.star)&&wa(a,h[1]))&&(a=h[1]+a.substring(h[3]));b=(S=a.match(/^([^\/]+)(\/(.+))?$/))?S[1]:"";(m=c[b])?a=b+"/"+(Ra=S[3]||m.main):b="";var q=0;r(l,function(b){var c=a.match(b[0]);c&&0<c.length&&(q=B(b[1])?a.replace(b[0],b[1]):b[1])});if(q)return Ua(q,0,c,d,e,g,f,l,p);if(c=d[a])return p?fa(c.pid,c.mid,c.pack,c.url):d[a];d=(h=wa(a,f))?h[1]+a.substring(h[3]):b?("/"===m.location.slice(-1)?m.location.slice(0,-1):m.location)+"/"+Ra:k("config-tlmSiblingOfDojo")?"../"+a:a;/(^\/)|(\:)/.test(d)||
(d=e+d);return fa(b,a,m,Ta(d+".js"))},Q=function(a,b,c){return Ua(a,b,C,m,f.baseUrl,c?[]:Z,c?[]:La,c?[]:Ka)},Va=function(a,b,c){return a.normalize?a.normalize(b,function(a){return va(a,c)}):va(b,c)},Wa=0,z=function(a,b,c){var d,e;(d=a.match(/^(.+?)\!(.*)$/))?(e=z(d[1],b,c),"sync"!=p||e.executed||(X(e),2!==e.injected||e.executed||P(function(){O(e)}),e.executed?ja(e):q.unshift(e)),5!==e.executed||e.load||ja(e),e.load?(d=Va(e,d[2],b),a=e.mid+"!"+(e.dynamic?++Wa+"!":"")+d):(d=d[2],a=e.mid+"!"+ ++Wa+"!waitingForPlugin"),
a={plugin:e,mid:a,req:ta(b),prid:d}):a=Q(a,b);return m[a.mid]||!c&&(m[a.mid]=a)},va=f.toAbsMid=function(a,b){return Q(a,b).mid},Na=f.toUrl=function(a,b){var c=Q(a+"/x",b),d=c.url;return Y(0===c.pid?a:d.substring(0,d.length-5))},Xa={injected:2,executed:5,def:3,result:3},xa=function(a){return m[a]=n({mid:a},Xa)},mb=xa("require"),nb=xa("exports"),ob=xa("module"),ka={},ya=0,ja=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},pb=function(a){var b={};r(a.loadQ,
function(c){var d=Va(a,c.prid,c.req.module),e=a.dynamic?c.mid.replace(/waitingForPlugin$/,d):a.mid+"!"+d,d=n(n({},c),{mid:e,prid:d,injected:0});m[e]&&m[e].injected||Ya(m[e]=d);b[c.mid]=m[e];J(c);delete m[c.mid]});a.loadQ=0;var c=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},d;for(d in m)c(m[d]);r(q,c)},N=function(a){f.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=ya++;r(a.provides,function(a){a()});a.loadQ&&(ja(a),pb(a));for(h=0;h<q.length;)q[h]===a?
q.splice(h,1):h++;/^require\*/.test(a.mid)&&delete m[a.mid]},qb=[],O=function(a,b){if(4===a.executed)return f.trace("loader-circular-dependency",[qb.concat(a.mid).join("-\x3e")]),!a.def||b?ka:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return ka;var c=a.mid,d=a.deps||[],e,g=[],l=0;for(a.executed=4;e=d[l++];){e=e===mb?ta(a):e===nb?a.cjs.exports:e===ob?a.cjs:O(e,b);if(e===ka)return a.executed=0,f.trace("loader-exec-module",["abort",c]),ka;g.push(e)}f.trace("loader-run-factory",[a.mid]);var c=a.def,
h;I.unshift(a);if(k("config-dojo-loader-catches"))try{h=B(c)?c.apply(null,g):c}catch(jb){v("error",a.result=u("factoryThrew",[a,jb]))}else h=B(c)?c.apply(null,g):c;a.result=void 0===h&&a.cjs?a.cjs.exports:h;I.shift(a);N(a)}return a.result},U=0,P=function(a){try{U++,a()}catch(b){throw b;}finally{U--}lb()&&v("idle",[])},M=function(){U||P(function(){pa();for(var a,b,c=0;c<q.length;)a=ya,b=q[c],O(b),a!=ya?(pa(),c=0):c++})},Y="function"==typeof l.fixupUrl?l.fixupUrl:function(a){a+="";return a+(sa?(/\?/.test(a)?
"\x26":"?")+sa:"")};void 0===k("dojo-loader-eval-hint-url")&&k.add("dojo-loader-eval-hint-url",1);var Ya=function(a){var b=a.plugin;5!==b.executed||b.load||ja(b);var c=function(b){a.result=b;J(a);N(a);M()};b.load?b.load(a.prid,a.req,c):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],q.unshift(b),X(b))},E=0,V=0,za=0,ga=function(a,b){k("config-stripStrict")&&(a=a.replace(/(["'])use strict\1/g,""));za=1;if(k("config-dojo-loader-catches"))try{a===E?E.call(null):f.eval(a,k("dojo-loader-eval-hint-url")?b.url:b.mid)}catch(c){v("error",
u("evalModuleThrew",b))}else a===E?E.call(null):f.eval(a,k("dojo-loader-eval-hint-url")?b.url:b.mid);za=0},X=function(a){var b=a.mid,c=a.url;if(!(a.executed||a.injected||t[b]||a.url&&(a.pack&&t[a.url]===a.pack||1==t[a.url])))if(kb(a),a.plugin)Ya(a);else{var d=function(){Za(a);if(2!==a.injected){if(k("dojo-enforceDefine")){v("error",u("noDefine",a));return}J(a);n(a,Xa);f.trace("loader-define-nonmodule",[a.url])}p?!I.length&&M():M()};if(E=D[b]||D["url:"+a.url])f.trace("loader-inject",["cache",a.mid,
c]),ga(E,a),d();else{if(p)if(a.isXd)"sync"==p&&(p="xd");else if(!a.isAmd||"sync"==p){var e=function(e){if("sync"==p){I.unshift(a);ga(e,a);I.shift();Za(a);a.cjs||(J(a),N(a));if(a.finish){e=b+"*finish";var g=a.finish;delete a.finish;Aa(e,["dojo",("dojo/require!"+g.join(",")).replace(/\./g,"/")],function(a){r(g,function(b){a.require(b)})});q.unshift(z(e))}d()}else(e=Ia(a,e))?(ga(e,a),d()):(V=a,f.injectUrl(Y(c),d,a),V=0)};f.trace("loader-inject",["xhr",a.mid,c,"sync"!=p]);if(k("config-dojo-loader-catches"))try{f.getText(c,
"sync"!=p,e)}catch(g){v("error",u("xhrInjectFailed",[a,g]))}else f.getText(c,"sync"!=p,e);return}f.trace("loader-inject",["script",a.mid,c]);V=a;f.injectUrl(Y(c),d,a);V=0}}},Ba=function(a,b,c){f.trace("loader-define-module",[a.mid,b]);var d=a.mid;if(2===a.injected)return v("error",u("multipleDefine",a)),a;n(a,{deps:b,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var e=0;b[e];e++)b[e]=z(b[e],a);p&&!t[d]&&(T(a),q.push(a),
M());J(a);B(c)||b.length||(a.result=c,N(a));return a},Za=function(a,b){for(var c=[],d,e;ha.length;)e=ha.shift(),b&&(e[0]=b.shift()),d=e[0]&&z(e[0])||a,c.push([d,e[1],e[2]]);ca(a);r(c,function(a){T(Ba.apply(null,a))})},la=0,ia=F,Sa=F,ia=function(){la&&clearTimeout(la);la=0},Sa=function(){ia();f.waitms&&(la=y.setTimeout(function(){ia();v("error",u("timeout",t))},f.waitms))};k.add("ie-event-behavior",w.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));
var Ca=function(a,b,c,d){if(k("ie-event-behavior"))return a.attachEvent(c,d),function(){a.detachEvent(c,d)};a.addEventListener(b,d,!1);return function(){a.removeEventListener(b,d,!1)}},rb=Ca(window,"load","onload",function(){f.pageLoaded=1;try{"complete"!=w.readyState&&(w.readyState="complete")}catch(a){}rb()}),da=w.getElementsByTagName("script");for(h=0;!K;)/^dojo/.test((A=da[h++])&&A.type)||(K=A);f.injectUrl=function(a,b,c){c=c.node=w.createElement("script");var d=Ca(c,"load","onreadystatechange",
function(a){a=a||window.event;var c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))d(),e(),b&&b()}),e=Ca(c,"error","onerror",function(b){d();e();v("error",u("scriptError",[a,b]))});c.type="text/javascript";c.charset="utf-8";c.src=a;K.parentNode.insertBefore(c,K);return c};f.log=function(){try{for(var a=0;a<arguments.length;a++);}catch(b){}};f.trace=F;var Aa=function(a,b,c){var d=arguments.length,e=["require","exports","module"],g=[0,a,b];1==d?g=[0,B(a)?e:[],a]:2==
d&&H(a)?g=[a,B(b)?e:[],b]:3==d&&(g=[a,b,c]);f.trace("loader-define",g.slice(0,2));if((d=g[0]&&z(g[0]))&&!t[d.mid])T(Ba(d,g[1],g[2]));else if(!k("ie-event-behavior")||za)ha.push(g);else{d=d||V;if(!d)for(a in t)if((e=m[a])&&e.node&&"interactive"===e.node.readyState){d=e;break}d?(ca(d),T(Ba(d,g[1],g[2]))):v("error",u("ieDefineFailed",g[0]));M()}};Aa.amd={vendor:"dojotoolkit.org"};n(n(f,x.loaderPatch),l.loaderPatch);gb("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(c){}});
n(f,{uid:Fa,cache:D,packs:C});if(y.define)v("error",u("defineAlreadyDefined",0));else{y.define=Aa;y.require=f;r(Qa,function(a){R(a)});var $a=ba.deps||l.deps||x.deps,ab=ba.callback||l.callback||x.callback;f.boot=$a||ab?[$a||[],ab]:0}})(function(l){return l.dojoConfig||l.djConfig||l.require||{}},{async:0,hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"}]});
(function(){var l=this.require;l({cache:{}});!l.async&&l(["dojo"]);l.boot&&l.apply(null,l.boot)})();